const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
let DATA=null,currentPage='dashboard',currentRange=localStorage.getItem('macrovisie-range')||'1J',tooltip,deferredPrompt,commandIndex=0;
const RANGE_MONTHS={'1M':1,'3M':3,'6M':6,'1J':12,'5J':60,'Alles':9999};
const PAGE_META={dashboard:['MACRO-OVERZICHT','Dashboard'],groei:['GROEI','Groei'],arbeidsmarkt:['ARBEIDSMARKT','Arbeidsmarkt'],inflatie:['INFLATIE','Inflatie'],ecb:['CENTRALE BANK','ECB & verwachtingen'],obligaties:['RENTE & INFLATIE','Obligaties'],liquiditeit:['GELD & KREDIET','Liquiditeit'],stress:['FINANCIËLE CONDITIES','Stress'],simulatie:['EXPERIMENTELE OMGEVING','Scenario-simulatie'],portefeuille:['PORTEFEUILLE-LAB','Portefeuille-stand'],valuation:['VALUATION-LAB','Valuation'],markten:['MARKTEN VERGELIJKEN','Eurozone versus VS'],regimes:['HISTORISCHE REGIMES','Historische regimes'],databeheer:['DATA & BRONNEN','Handmatige data'],cheatsheet:['VASTE VERTAALTABEL','Cheat sheet'],begrippen:['NASLAG','Begrippen']};
const PAGE_KEYS={groei:['pmiManufacturing','pmiServices','pmiComposite','gdp'],arbeidsmarkt:['unemployment','wages'],inflatie:['cpi','coreCpi'],ecb:['depositRate','oisCuts3m','oisCuts6m','oisCuts12m'],obligaties:['yield2y','yield5y','yield10y','yield30y','aaaYield2y','aaaYield5y','aaaYield10y','aaaYield30y','bund2y','bund5y','bund10y','bund30y','yieldCurve','realYield','inflationProxy','marketInflation5y5y'],liquiditeit:['m3','ecbBalance'],stress:['creditSpread']};
const DASH_KEYS=['pmiComposite','unemployment','coreCpi','depositRate','oisCuts12m','yield10y','realYield','inflationProxy','marketInflation5y5y','m3','creditSpread'];
const TARGET_PAGE={pmiManufacturing:'groei',pmiServices:'groei',pmiComposite:'groei',gdp:'groei',unemployment:'arbeidsmarkt',wages:'arbeidsmarkt',cpi:'inflatie',coreCpi:'inflatie',depositRate:'ecb',oisCuts3m:'ecb',oisCuts6m:'ecb',oisCuts12m:'ecb',yield2y:'obligaties',yield5y:'obligaties',yield10y:'obligaties',yield30y:'obligaties',yieldCurve:'obligaties',realYield:'obligaties',breakeven:'obligaties',inflationProxy:'obligaties',marketInflation5y5y:'inflatie',aaaYield2y:'obligaties',aaaYield5y:'obligaties',aaaYield10y:'obligaties',aaaYield30y:'obligaties',bund2y:'obligaties',bund5y:'obligaties',bund10y:'obligaties',bund30y:'obligaties',m3:'liquiditeit',ecbBalance:'liquiditeit',creditSpread:'stress'};
const DEFINITIONS={
 pmiManufacturing:['PMI Manufacturing','Een maandelijkse enquête onder industriële bedrijven. Boven 50 wijst meestal op uitbreiding; onder 50 op krimp. De richting is minstens zo belangrijk als het niveau.'],
 pmiServices:['PMI Services','Een enquête onder dienstverleners. Voor de eurozone is deze vaak belangrijker voor de totale groei dan de industriële PMI.'],
 pmiComposite:['PMI Composite','Een combinatie van industrie en diensten. Dit is een bruikbare, vroege samenvatting van de conjunctuur.'],
 gdp:['BBP-groei','De gerealiseerde economische groei. BBP is betrouwbaarder dan een enquête, maar verschijnt later en wordt geregeld herzien.'],
 unemployment:['Werkloosheid','Een lage werkloosheid wijst op een krappe arbeidsmarkt. Veranderingen in de trend zijn vaak belangrijker dan één los cijfer.'],
 wages:['Loonontwikkeling','Lonen beïnvloeden vooral de diensteninflatie. Hoge loongroei kan de ECB voorzichtig maken met renteverlagingen.'],
 cpi:['CPI / HICP','De totale consumentenprijsinflatie, inclusief voedsel en energie. Deze reeks kan sterk bewegen door energieprijzen.'],
 coreCpi:['Kerninflatie','Inflatie zonder de meest volatiele componenten. Ze geeft een beter beeld van de onderliggende prijsdruk.'],
 depositRate:['ECB-depositorente','De rente die banken ontvangen op deposito’s bij de ECB. Dit is de belangrijkste beleidsrente voor de eurozone.'],
 oisCuts3m:['OIS 3 maanden','Ingeprijsde netto ECB-stappen over circa drie maanden. Positief = verlagingen; negatief = verhogingen. Eén stap is 25 basispunten.'],
 oisCuts6m:['OIS 6 maanden','Ingeprijsde netto ECB-stappen over circa zes maanden. Positief = verlagingen; negatief = verhogingen. Eén stap is 25 basispunten.'],
 oisCuts12m:['OIS 12 maanden','Ingeprijsde netto ECB-stappen over circa twaalf maanden. Positief = verlagingen; negatief = verhogingen. Eén stap is 25 basispunten.'],
 yieldCurve:['10Y–2Y rentecurve','Het verschil tussen de 10- en 2-jaarsrente. Een negatieve waarde heet een inverse rentecurve en wijst vaak op verwachte toekomstige renteverlagingen.'],
 realYield:['Reële yield','De nominale yield na aftrek van verwachte inflatie. Een stijgende reële rente is meestal negatief voor goud en voor langlopende duration.'],
 breakeven:['Inflatiecompensatie (proxy)','ECB nominale benchmark minus ECB reële benchmark. Dit is geen zuivere, verhandelbare break-even.'],
 inflationProxy:['Afgeleide inflatiecompensatie','Nominale eurozone-benchmark minus reële eurozone-benchmark. Door verschillen in instrumenten en liquiditeit is dit alleen een proxy.'],
 marketInflation5y5y:['5Y5Y-inflatieswap','Een marktmaat voor de gemiddelde inflatie over vijf jaar, beginnend over vijf jaar. Dit is een inflatiecompensatiemaat: verwachting plus risicopremie.'],
 aaaYield10y:['AAA-eurozonecurve','ECB-modelcurve voor staatsobligaties van alle AAA-emittenten in de eurozone. Dit is niet uitsluitend Duitsland.'],
 bund10y:['Duitse Bund','Rendement van de meest recente Duitse federale obligatie met de aangegeven oorspronkelijke looptijd, rechtstreeks van de Bundesbank.'],
 m3:['M3-groei','Een brede maatstaf voor geld in de economie. M3 omvat M1 plus onder meer deposito’s en bepaalde geldmarktinstrumenten.'],
 ecbBalance:['ECB-balans','De omvang van bezittingen op de Eurosysteembalans. Een krimpende balans wijst doorgaans op QT en minder centrale-bankliquiditeit.'],
 creditSpread:['Euro High Yield OAS','De option-adjusted spread van euro-bedrijfsobligaties onder investment grade. Een stijging wijst op meer kredietstress en strengere financiële condities.'],

 trailingPE:['Trailing K/W','De koers gedeeld door de gerealiseerde winst over de afgelopen twaalf maanden. Een lagere waarde kan op een goedkopere markt wijzen, maar ook op zwakkere groei of hoger risico.'],
 forwardPE:['Forward K/W','De koers gedeeld door de door analisten verwachte winst over de komende twaalf maanden. Deze maat kijkt vooruit, maar is afhankelijk van winstverwachtingen die kunnen worden bijgesteld.'],
 earningsYield:['Earnings yield','Het omgekeerde van de forward koers-winstverhouding: 100 gedeeld door de forward K/W. Bij een forward K/W van 15 is de earnings yield 6,67%. Het is de verwachte winst als percentage van de marktwaarde, niet het dividend en geen gegarandeerd rendement.'],
 dividendYield:['Dividendrendement','Het verwachte of gerealiseerde dividend als percentage van de beurswaarde. Dividend is slechts één deel van het totale aandeelhoudersrendement en kan worden verlaagd.'],
 earningsSpread:['Premie boven 10Y','De earnings yield minus de gebruikte 10-jaarsrente. Een grotere positieve premie betekent dat aandelen op deze eenvoudige maat meer winstvergoeding bieden dan obligaties. Dit is geen volledige equity risk premium.'],
 valuationReading:['Waardering lezen','Lagere K/W en hogere earnings yield wijzen meestal op een lagere waardering. Goedkoop is niet automatisch aantrekkelijk: lagere groei, cyclische winsten, leverage en structurele risico’s kunnen een korting verklaren. Vergelijk daarom meerdere maten en de eigen historie.'],
 valuationFreshness:['Actualiteit van waarderingsdata','Indexwaarderingen zijn fundamentele gegevens en worden meestal maandelijks gepubliceerd. De actuele koers beweegt dagelijks, maar winstverwachtingen en indexfactsheets worden minder vaak bijgewerkt. Daarom toont MacroVisie altijd de peildatum.'],
 pricingPowerProxy:['Prijszettingsmacht-proxy','Er bestaat geen universele, vrij beschikbare prijszettingsmacht-index. MSCI EMU Universal wordt hier gebruikt als proxy voor robuustere ondernemingen. Zie dit niet als een zuivere selectie van bedrijven met aantoonbare prijszettingsmacht.'],
};
const STATUS_CONFIG=[['Groei',['pmiComposite','gdp']],['Arbeidsmarkt',['unemployment','wages']],['Inflatie',['coreCpi','cpi']],['ECB',['depositRate','oisCuts12m']],['Liquiditeit',['m3','ecbBalance']],['Stress',['creditSpread']]];
function fmtDate(d){if(!d)return'—';return new Date(d).toLocaleDateString('nl-NL',{month:'short',year:'numeric'})}
function seriesValid(s){return Boolean(s?.values?.length)&&s.data_quality!==false&&s.freshness!=='fout'}
function latest(s){return seriesValid(s)?s.values.at(-1):null}
function formatValue(v,u=''){if(v==null||Number.isNaN(v))return'—';let value=v;if(u==='€ mld'&&Math.abs(value)>100000)value/=1000;const digits=u==='€ mld'?0:Math.abs(value)<10?2:1;const n=value.toLocaleString('nl-NL',{minimumFractionDigits:u==='€ mld'?0:Math.abs(value)<10?1:0,maximumFractionDigits:digits});if(u==='stappen')return`${n} stappen`;if(u==='€ mld')return`€ ${n} mld`;return`${n}${u||''}`}
function monthsBack(date,n){const d=new Date(date);d.setMonth(d.getMonth()-n);return d}
function filtered(s){if(!s?.values?.length)return[];if(currentRange==='Alles')return s.values;const end=new Date(s.values.at(-1).date),start=monthsBack(end,RANGE_MONTHS[currentRange]);return s.values.filter(v=>new Date(v.date)>=start)}
function deltaAt(s,m){const vals=s?.values||[];if(vals.length<2)return null;const end=vals.at(-1),target=monthsBack(new Date(end.date),m);let prev=vals[0];for(const v of vals){if(new Date(v.date)<=target)prev=v;else break}return end.value-prev.value}
function sourceClass(src=''){src=src.toLowerCase();return src.includes('hand')?'manual':src.includes('afgeleid')||src.includes('berekend')||src.includes('proxy')?'calculated':'live'}
function trendClass(v){if(v==null||Math.abs(v)<.0001)return'flat';return v>0?'up':'down'}
function niceRange(min,max){if(min===max){min-=1;max+=1}const pad=(max-min)*.13||1;return[min-pad,max+pad]}
function scoreClamp(x){return Math.max(0,Math.min(100,x))}
function metricMomentum(key){const s=DATA.series[key],d=deltaAt(s,3);return d==null?0:d}
function pulseData(){
 const val=k=>latest(DATA.series[k])?.value;
 const pmi=val('pmiComposite'),gdp=val('gdp'),un=val('unemployment');
 const core=val('coreCpi'),cpi=val('cpi'),wages=val('wages');
 const dep=val('depositRate'),ois=val('oisCuts12m');
 const spread=val('creditSpread'),m3=val('m3'),bal=seriesValid(DATA.series.ecbBalance)?metricMomentum('ecbBalance'):null;
 const part=(name,score,value)=>value==null?null:[name,scoreClamp(score),value];
 const clean=parts=>parts.filter(Boolean);
 const growthParts=clean([part('PMI composite',50+(pmi-50)*10,pmi),part('BBP k/k',50+gdp*35,gdp),part('Werkloosheid',75-(un-6)*15,un)]);
 const inflationParts=clean([part('Kerninflatie',(core-1)*35,core),part('Headline HICP',(cpi-1)*28,cpi),part('Lonen',(wages-2)*24,wages)]);
 const policyParts=clean([part('Depositorente',dep*24,dep),part('Ingeprijsde cuts',65-ois*12,ois),part('Kerninflatie',(core-1)*35,core)]);
 const financeParts=clean([part('M3-groei',45+m3*8,m3),part('Credit spread',85-spread*24,spread),part('Balansmomentum',50+bal/20,bal)]);
 const avg=parts=>parts.length?parts.reduce((sum,x)=>sum+x[1],0)/parts.length:null;
 return [
  {name:'Groei',score:avg(growthParts),caption:pmi==null?'onvoldoende data':pmi>=50?'uitbreiding':'vertraging',parts:growthParts},
  {name:'Inflatiedruk',score:avg(inflationParts),caption:core==null&&cpi==null?'inflatiebron niet beschikbaar':core>2.3?'boven doel':'richting doel',parts:inflationParts},
  {name:'Beleidsdruk',score:avg(policyParts),caption:dep==null?'onvoldoende data':dep>2?'restrictief':'minder restrictief',parts:policyParts},
  {name:'Financiële ruimte',score:avg(financeParts),caption:spread==null?'onvoldoende data':spread>1.5?'krapper':'redelijk ruim',parts:financeParts}
 ]
}
function statusFor(name,keys){
 const vals=keys.map(k=>latest(DATA.series[k])?.value).filter(v=>v!=null);let label='Gemengd',cls='warn',sub='signalen verdeeld';
 if(name==='Groei'){const p=latest(DATA.series.pmiComposite)?.value||50,g=latest(DATA.series.gdp)?.value||0;if(p>=50&&g>=0){label='Groei';cls='good';sub='activiteit positief'}else if(p<49&&g<0){label='Zwak';cls='bad';sub='activiteit krimpt'}}
 if(name==='Arbeidsmarkt'){const u=latest(DATA.series.unemployment)?.value||0,w=latest(DATA.series.wages)?.value||0;if(u<7&&w>3){label='Krap';cls='warn';sub='loondruk aanwezig'}else if(u>8){label='Ruimer';cls='good';sub='minder loondruk'}}
 if(name==='Inflatie'){const c=latest(DATA.series.coreCpi)?.value;if(c==null){label='Geen geldige data';cls='warn';sub='Eurostat-bron controleren'}else if(c>2.7){label='Hardnekkig';cls='bad';sub='kern boven doel'}else if(c<=2.2){label='Dicht bij doel';cls='good';sub='druk neemt af'}}
 if(name==='ECB'){const r=latest(DATA.series.depositRate)?.value||0,o=latest(DATA.series.oisCuts12m)?.value||0;if(o>=2){label='Cuts ingeprijsd';cls='warn';sub=`${formatValue(o,'stappen')}`}else if(r>2){label='Restrictief';cls='bad';sub='rente nog hoog'}}
 if(name==='Liquiditeit'){const m=metricMomentum('m3'),b=metricMomentum('ecbBalance');if(m>0&&b>0){label='Ruimer';cls='good';sub='geld en balans groeien'}else if(m<0&&b<0){label='Krapper';cls='bad';sub='beide dalen'}}
 if(name==='Stress'){const s=latest(DATA.series.creditSpread)?.value||0;if(s<3){label='Laag';cls='good';sub='HY-spread beperkt'}else if(s>5){label='Hoog';cls='bad';sub='HY-spread breed'}}
 return{label,cls,sub}
}
function sparkSvg(series){const vals=filtered(series).slice(-18);if(vals.length<2)return'';const W=88,H=32,min=Math.min(...vals.map(v=>v.value)),max=Math.max(...vals.map(v=>v.value)),x=i=>i/(vals.length-1)*W,y=v=>H-3-(v-min)/(max-min||1)*(H-7),d=vals.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(v.value).toFixed(1)}`).join(' ');return`<svg class="sparkline" viewBox="0 0 ${W} ${H}" aria-hidden="true"><path class="spark-area" d="${d} L${W},${H} L0,${H} Z"/><path d="${d}"/></svg>`}
function renderPulse(){$('#pulseGrid').innerHTML=pulseData().map(x=>{const ok=x.score!=null,score=ok?Math.round(x.score):0;return`<details class="pulse-item"><summary><div class="pulse-item-head"><strong>${x.name}</strong><span>${ok?score+'/100':'—'}</span></div><div class="pulse-track"><div class="pulse-fill" style="width:${score}%"></div></div><div class="pulse-caption">${x.caption}${x.parts.length?' · tik voor berekening':''}</div></summary><div class="score-breakdown">${x.parts.length?x.parts.map(p=>`<div><span>${p[0]}</span><strong>${formatValue(p[2],p[0].includes('PMI')?'':'')}</strong><em>${Math.round(p[1])}/100</em></div>`).join(''):'<p>Geen gevalideerde brondata beschikbaar.</p>'}</div></details>`}).join('')}
function renderStatus(){$('#statusGrid').innerHTML=STATUS_CONFIG.map(([name,keys])=>{const s=statusFor(name,keys);return`<article class="card status-card ${s.cls}"><small>${name}</small><strong>${s.label}</strong><span>${s.sub}</span></article>`}).join('')}
function metricCard(key,clickable=false){const s=DATA.series[key]||{label:key,unit:'',source:'niet beschikbaar',values:[]},l=latest(s),d=deltaAt(s,1),tc=trendClass(d),arrow=tc==='up'?'▲':tc==='down'?'▼':'—',target=TARGET_PAGE[key];return`<article class="card metric-card" ${clickable&&target?`data-target="${target}" tabindex="0" role="link"`:''}><div class="metric-top"><span class="metric-label">${s.label}</span><span class="source-tag ${sourceClass(s.source)} ${s.freshness==='verouderd'?'stale':''}" title="${s.source_name||s.source||''}">${s.data_quality===false||s.freshness==='fout'?'NIET BESCHIKBAAR':s.freshness==='verouderd'?'VEROUDERD':s.source||'demo'}</span></div><div class="metric-value"><strong>${formatValue(l?.value,s.unit)}</strong></div><div class="metric-date">${fmtDate(l?.date)}</div><div class="metric-bottom"><span class="metric-change ${tc}">${arrow} ${d==null?'geen vergelijking':formatValue(Math.abs(d),s.unit)} m/m</span>${sparkSvg(s)}</div><div class="confidence-badge ${confidenceFor(s)[1]}">Confidence: ${confidenceFor(s)[0]}</div></article>`}
function renderCards(){$('#dashboardMetrics').innerHTML=DASH_KEYS.map(k=>metricCard(k,true)).join('');$$('[data-page-metrics]').forEach(el=>{el.innerHTML=(PAGE_KEYS[el.dataset.pageMetrics]||[]).map(k=>metricCard(k)).join('')});$$('.metric-card[data-target]').forEach(el=>{const go=()=>location.hash=el.dataset.target;el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})}
function svgChart(el,series){series=series.filter(Boolean).map(s=>({s,vals:filtered(s)})).filter(o=>o.vals.length);if(!series.length){el.innerHTML='<div class="chart-empty">Geen data voor deze periode</div>';return}const W=760,H=300,p={l:48,r:18,t:24,b:38},all=series.flatMap(o=>o.vals.map(v=>v.value)),dates=series.flatMap(o=>o.vals.map(v=>new Date(v.date).getTime())),[min,max]=niceRange(Math.min(...all),Math.max(...all)),xmin=Math.min(...dates),xmax=Math.max(...dates),x=t=>p.l+(t-xmin)/(xmax-xmin||1)*(W-p.l-p.r),y=v=>p.t+(max-v)/(max-min)*(H-p.t-p.b);let grid='';for(let i=0;i<5;i++){const val=max-i*(max-min)/4,yy=y(val);grid+=`<line class="grid-line" x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}"/><text class="axis-label" x="${p.l-8}" y="${yy+4}" text-anchor="end">${val.toFixed(1)}</text>`}if(min<0&&max>0)grid+=`<line class="zero-line" x1="${p.l}" x2="${W-p.r}" y1="${y(0)}" y2="${y(0)}"/>`;const threshold=series.find(o=>o.s.threshold!=null)?.s.threshold;if(threshold!=null&&threshold>=min&&threshold<=max)grid+=`<line class="threshold-line" x1="${p.l}" x2="${W-p.r}" y1="${y(threshold)}" y2="${y(threshold)}"/>`;
 const paths=series.map((o,i)=>{const pts=o.vals.map(v=>[x(new Date(v.date).getTime()),y(v.value)]),d=pts.map((q,j)=>`${j?'L':'M'}${q[0].toFixed(1)},${q[1].toFixed(1)}`).join(' '),area=i===0?`<path class="area-fill" d="${d} L${pts.at(-1)[0]},${H-p.b} L${pts[0][0]},${H-p.b} Z"/>`:'';const dots=o.vals.map(v=>`<circle class="hover-dot" cx="${x(new Date(v.date).getTime())}" cy="${y(v.value)}" r="10" fill="transparent" data-date="${v.date}" data-value="${v.value}" data-unit="${o.s.unit||''}" data-label="${o.s.label}"/>`).join('');return`${area}<path class="series-line ${i?'secondary':''}" d="${d}"/>${dots}`}).join('');
 const start=new Date(xmin),end=new Date(xmax);el.innerHTML=`${series.length>1?`<div class="legend">${series.map((o,i)=>`<span><i class="${i?'secondary':''}"></i>${o.s.label}</span>`).join('')}</div>`:''}<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--accent)" stop-opacity=".22"/><stop offset="100%" stop-color="var(--accent)" stop-opacity="0"/></linearGradient></defs><g>${grid}${paths}<text class="axis-label" x="${p.l}" y="${H-8}">${start.toLocaleDateString('nl-NL',{month:'short',year:'2-digit'})}</text><text class="axis-label" x="${W-p.r}" y="${H-8}" text-anchor="end">${end.toLocaleDateString('nl-NL',{month:'short',year:'2-digit'})}</text></g></svg>`;$$('.hover-dot',el).forEach(dot=>{dot.addEventListener('pointerenter',e=>showTooltip(e,`${dot.dataset.label}<br><strong>${formatValue(Number(dot.dataset.value),dot.dataset.unit)}</strong><br>${fmtDate(dot.dataset.date)}`));dot.addEventListener('pointermove',moveTooltip);dot.addEventListener('pointerleave',hideTooltip)})}
function renderCharts(){$$('[data-chart]').forEach(el=>svgChart(el,[DATA.series[el.dataset.chart]]));$$('[data-multi-chart]').forEach(el=>svgChart(el,el.dataset.multiChart.split(',').map(k=>DATA.series[k])));renderYieldCurve();renderSafeYieldCurve()}
function renderYieldCurve(){const el=$('#yieldCurveChart');if(!el)return;const points=[[2,latest(DATA.series.yield2y)?.value],[5,latest(DATA.series.yield5y)?.value],[10,latest(DATA.series.yield10y)?.value],[30,latest(DATA.series.yield30y)?.value]].filter(x=>x[1]!=null);if(points.length<2){el.innerHTML='<div class="chart-empty">Geen yieldcurve-data</div>';return}const W=760,H=300,p={l:48,r:18,t:28,b:38},[min,max]=niceRange(Math.min(...points.map(x=>x[1])),Math.max(...points.map(x=>x[1]))),x=m=>p.l+(m-2)/28*(W-p.l-p.r),y=v=>p.t+(max-v)/(max-min)*(H-p.t-p.b);let grid='';for(let i=0;i<5;i++){const val=max-i*(max-min)/4,yy=y(val);grid+=`<line class="grid-line" x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}"/><text class="axis-label" x="${p.l-8}" y="${yy+4}" text-anchor="end">${val.toFixed(2)}</text>`}const d=points.map((q,i)=>`${i?'L':'M'}${x(q[0])},${y(q[1])}`).join(' '),dots=points.map(q=>`<circle class="focus-dot" cx="${x(q[0])}" cy="${y(q[1])}" r="5"/><text class="axis-label" x="${x(q[0])}" y="${H-10}" text-anchor="middle">${q[0]}Y</text><text class="axis-label" x="${x(q[0])}" y="${y(q[1])-12}" text-anchor="middle">${q[1].toFixed(2)}%</text>`).join('');el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}<path class="series-line" d="${d}"/>${dots}</svg>`}

function renderSafeYieldCurve(){const el=$('#safeYieldCurveChart');if(!el)return;const sets=[{name:'AAA eurozone',keys:['aaaYield2y','aaaYield5y','aaaYield10y','aaaYield30y'],cls:''},{name:'Duitse federale effecten',keys:['bund2y','bund5y','bund10y','bund30y'],cls:'secondary'}];const maturities=[2,5,10,30],all=sets.flatMap(set=>set.keys.map(k=>latest(DATA.series[k])?.value).filter(v=>v!=null));if(all.length<2){el.innerHTML='<div class="chart-empty">De bron wordt bij de volgende update gevuld.</div>';return}const W=760,H=310,p={l:50,r:20,t:42,b:42},[min,max]=niceRange(Math.min(...all),Math.max(...all)),x=m=>p.l+(m-2)/28*(W-p.l-p.r),y=v=>p.t+(max-v)/(max-min)*(H-p.t-p.b);let grid='';for(let i=0;i<5;i++){const val=max-i*(max-min)/4,yy=y(val);grid+=`<line class="grid-line" x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}"/><text class="axis-label" x="${p.l-8}" y="${yy+4}" text-anchor="end">${val.toLocaleString('nl-NL',{maximumFractionDigits:2})}</text>`}let paths='';sets.forEach(set=>{const pts=set.keys.map((k,i)=>[maturities[i],latest(DATA.series[k])?.value]).filter(x=>x[1]!=null);if(pts.length<2)return;const d=pts.map((q,i)=>`${i?'L':'M'}${x(q[0])},${y(q[1])}`).join(' ');paths+=`<path class="series-line ${set.cls}" d="${d}"/>`+pts.map(q=>`<circle class="focus-dot ${set.cls}" cx="${x(q[0])}" cy="${y(q[1])}" r="5"/><text class="axis-label" x="${x(q[0])}" y="${y(q[1])-11}" text-anchor="middle">${q[1].toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}%</text>`).join('')});el.innerHTML=`<div class="legend"><span><i></i>AAA eurozone</span><span><i class="secondary"></i>Duitse federale effecten</span></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}${paths}${maturities.map(m=>`<text class="axis-label" x="${x(m)}" y="${H-12}" text-anchor="middle">${m}Y</text>`).join('')}</svg>`}
function deltaChip(v,u=''){if(v==null)return'<span class="delta-chip flat">—</span>';const cls=trendClass(v),sign=v>0?'+':'';return`<span class="delta-chip ${cls}">${sign}${formatValue(v,u)}</span>`}
function renderMonitor(){const keys=['pmiComposite','unemployment','coreCpi','depositRate','yield10y','realYield','m3','creditSpread'];$('#monitorTable').innerHTML=keys.map(k=>{const s=DATA.series[k],l=latest(s);return`<tr><td>${s.label}</td><td><strong>${formatValue(l?.value,s.unit)}</strong></td><td>${deltaChip(deltaAt(s,1),s.unit)}</td><td>${deltaChip(deltaAt(s,3),s.unit)}</td><td>${deltaChip(deltaAt(s,12),s.unit)}</td><td><span class="source-tag ${sourceClass(s.source)} ${s.freshness==='verouderd'?'stale':''}" title="${s.source_name||s.source||''}">${s.data_quality===false||s.freshness==='fout'?'NIET BESCHIKBAAR':s.freshness==='verouderd'?'VEROUDERD':s.source||'demo'}</span></td></tr>`}).join('')}
function renderGrowthTable(){const keys=['pmiManufacturing','pmiServices','pmiComposite','gdp'],periods=[...new Set(keys.flatMap(k=>filtered(DATA.series[k]).map(v=>v.date)))].sort().slice(-14).reverse();$('#growthTable').innerHTML=periods.map(d=>`<tr><td>${fmtDate(d)}</td>${keys.map(k=>`<td>${DATA.series[k].values.find(v=>v.date===d)?.value?.toLocaleString('nl-NL',{maximumFractionDigits:2})??'—'}</td>`).join('')}</tr>`).join('')}
function renderPolicy(){const vals=filtered(DATA.series.ecbBalance);if(vals.length<2)return;const delta=vals.at(-1).value-vals[0].value;$('#policyLabel').textContent=delta<0?'QT — balans krimpt':'QE / ruimere liquiditeit — balans groeit';$('#policyText').textContent=delta<0?'De ECB-balans is over de gekozen periode kleiner geworden. Dat wijst op liquiditeitsverkrapping.':'De ECB-balans is over de gekozen periode groter geworden. Dat wijst op extra centrale-bankliquiditeit.'}
function renderFormula(){const n=latest(DATA.series.yield10y)?.value,r=latest(DATA.series.realYield)?.value,b=latest(DATA.series.inflationProxy||DATA.series.breakeven)?.value;$('#breakevenFormula').textContent=[n,r,b].every(v=>v!=null)?`${n.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}% − ${r.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}% = ${b.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}%`:'—'}
function renderDefinitions(){$('#definitions').innerHTML=Object.entries(DEFINITIONS).map(([k,[t,d]])=>`<article class="card definition"><span class="eyebrow">${DATA.series[k]?.category||'BEGRIP'}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}
function renderAll(){renderRecession();renderPulse();renderStatus();renderCards();renderCharts();renderGrowthTable();renderMonitor();renderPolicy();renderFormula();renderExpectations();renderDataAudit();renderPortfolio()}

const PORTFOLIO_ASSETS=[['growthStocks','Groei-aandelen'],['valueStocks','Value-aandelen'],['pricingPower','Aandelen met prijszettingsmacht'],['em','Opkomende markten'],['realEstate','Vastgoed'],['commodities','Grondstoffen'],['longGov','Langlopende staatsobligaties'],['shortGov','Kortlopende staatsobligaties'],['inflationLinked','Inflatiegelinkte obligaties'],['ig','Investment Grade'],['hy','High Yield'],['gold','Goud'],['moneyMarket','Geldmarkt'],['euroCash','Euro/cash']];
const PORTFOLIO_DEFAULT={growthStocks:12,valueStocks:12,pricingPower:12,em:5,realEstate:5,commodities:5,longGov:8,shortGov:8,inflationLinked:8,ig:7,hy:3,gold:7,moneyMarket:4,euroCash:4};
const PORT_SENS={
 growthStocks:[1.0,-.35,-1.0,.75,-.65],valueStocks:[.7,.1,-.25,.35,-.45],pricingPower:[.75,.55,-.45,.45,-.35],em:[1.05,.25,-.75,.8,-.9],realEstate:[.55,.35,-1.05,.45,-.7],commodities:[.3,1.0,.05,.25,.2],longGov:[-.55,-.85,-1.2,.25,.35],shortGov:[-.15,-.25,-.3,.15,.1],inflationLinked:[-.15,.9,-.8,.25,.2],ig:[.35,-.2,-.55,.55,-.85],hy:[.9,-.05,-.45,.7,-1.2],gold:[-.2,.5,-.75,.65,.45],moneyMarket:[-.05,-.1,.35,.05,.05],euroCash:[-.05,-.15,.45,-.1,.05]
};
const PORT_VOL={growthStocks:22,valueStocks:17,pricingPower:16,em:25,realEstate:20,commodities:22,longGov:14,shortGov:5,inflationLinked:11,ig:7,hy:12,gold:16,moneyMarket:1,euroCash:.5};
const PORT_BUCKET={growthStocks:'equity',valueStocks:'equity',pricingPower:'equity',em:'equity',realEstate:'real',commodities:'real',longGov:'duration',shortGov:'duration',inflationLinked:'inflation',ig:'credit',hy:'credit',gold:'real',moneyMarket:'cash',euroCash:'cash'};
function assumedCorrelation(a,b){if(a===b)return 1;const A=PORT_BUCKET[a],B=PORT_BUCKET[b];if(A===B)return A==='cash'?.75:.65;const key=[A,B].sort().join('-');return {'duration-equity':-.15,'equity-inflation':.15,'equity-real':.35,'credit-equity':.65,'credit-duration':.25,'duration-inflation':.25,'duration-real':-.1,'inflation-real':.45,'credit-real':.25,'cash-equity':0,'cash-duration':.05,'cash-credit':.05,'cash-real':0,'cash-inflation':.05}[key]??.15;}
function portfolioState(){try{return{...PORTFOLIO_DEFAULT,...JSON.parse(localStorage.getItem('macrovisie-portfolio')||'{}')}}catch{return{...PORTFOLIO_DEFAULT}}}
function renderPortfolio(){const root=$('#portfolioInputs');if(!root)return;const state=portfolioState();if(!root.children.length){root.innerHTML=PORTFOLIO_ASSETS.map(([id,label])=>`<label><span>${label}</span><input type="number" min="0" max="100" step="0.5" value="${state[id]||0}" data-portfolio="${id}"><em>%</em></label>`).join('');root.addEventListener('input',()=>{const now={};$$('[data-portfolio]',root).forEach(i=>now[i.dataset.portfolio]=Number(i.value)||0);localStorage.setItem('macrovisie-portfolio',JSON.stringify(now));renderPortfolio()});$('#portfolioReset')?.addEventListener('click',()=>{localStorage.setItem('macrovisie-portfolio',JSON.stringify(PORTFOLIO_DEFAULT));root.innerHTML='';renderPortfolio()})}const total=Object.values(state).reduce((a,b)=>a+b,0);$('#portfolioTotal').textContent=formatValue(total,'%');$('#portfolioTotal').className=Math.abs(total-100)<.01?'good-text':'bad-text';const palette=['#7cc6ff','#89e0c1','#a8b8ff','#c4a7ff','#63d7d1','#f3b568','#f0d26f','#9aa9bd','#6fc3a0','#df9f72','#b6a7ff','#e7ca75','#91a5bc','#d3dae5'],stops=[];let cursor=0;PORTFOLIO_ASSETS.forEach(([id],i)=>{const share=total?state[id]/total*100:0;stops.push(`${palette[i%palette.length]} ${cursor}% ${cursor+share}%`);cursor+=share});$('#portfolioDonut').style.background=`conic-gradient(${stops.join(',')})`;$('#portfolioDonut').innerHTML=`<span>${formatValue(total,'%')}</span>`;$('#portfolioLegend').innerHTML=PORTFOLIO_ASSETS.map(([id,label],i)=>`<div><i style="background:${palette[i%palette.length]}"></i><span>${label}</span><strong>${formatValue(state[id],'%')}</strong></div>`).join('');const factors=['Groei','Inflatie','Reële rente','Liquiditeit','Stress'],scores=factors.map((_,j)=>PORTFOLIO_ASSETS.reduce((sum,[id])=>sum+(state[id]/Math.max(total,1))*PORT_SENS[id][j],0));$('#portfolioSensitivity').innerHTML=factors.map((f,i)=>{const pct=Math.min(100,Math.abs(scores[i])*75),dir=scores[i]>.12?'profiteert van stijging':scores[i]<-.12?'kwetsbaar bij stijging':'vrij neutraal';return`<div><span>${f}</span><div class="sensitivity-track"><i class="${scores[i]>=0?'positive':'negative'}" style="width:${pct}%"></i></div><small>${dir}</small></div>`}).join('');const ranked=factors.map((f,i)=>[f,scores[i]]).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));$('#portfolioCommentary').innerHTML=`<p>De grootste macrogevoeligheid is <strong>${ranked[0][0].toLowerCase()}</strong>. Dit zijn vaste scenario-elasticiteiten, geen rendementsverwachtingen.</p><p>${Math.abs(total-100)>.01?`De allocatie telt op tot <strong>${formatValue(total,'%')}</strong>; pas dit aan naar 100%.`:'De allocatie telt op tot 100%.'}</p>`;renderHolyGrail(state,total)}
function renderHolyGrail(state,total){const active=PORTFOLIO_ASSETS.map(([id,label])=>({id,label,w:(state[id]||0)/Math.max(total,1),vol:PORT_VOL[id]})).filter(x=>x.w>.002);const risk=active.map(x=>x.w*x.vol),riskSum=risk.reduce((a,b)=>a+b,0)||1,shares=risk.map(x=>x/riskSum);const nEff=shares.length?1/shares.reduce((s,x)=>s+x*x,0):0;let corrNum=0,corrDen=0;for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const w=shares[i]*shares[j];corrNum+=w*assumedCorrelation(active[i].id,active[j].id);corrDen+=w}const rho=corrDen?corrNum/corrDen:1;const relativeVol=nEff?Math.sqrt(Math.max(.01,(1+(nEff-1)*rho)/nEff)):1;const score=Math.round(Math.max(0,Math.min(100,(1-relativeVol)/.75*100)));$('#holyGrailScore').textContent=score;$('#holyGrailDetails').innerHTML=`<p><strong>${nEff.toLocaleString('nl-NL',{maximumFractionDigits:1})}</strong> effectieve, risicogewogen inkomstenstromen · gemiddelde correlatie <strong>${rho.toLocaleString('nl-NL',{style:'percent',maximumFractionDigits:0})}</strong>.</p><p>Dalio-curve: relatieve volatiliteit circa <strong>${relativeVol.toLocaleString('nl-NL',{style:'percent',maximumFractionDigits:0})}</strong> van één vergelijkbare risicostroom.</p>`;const top=[...active].sort((a,b)=>b.w-a.w).slice(0,7);$('#correlationMatrix').innerHTML='<table><thead><tr><th></th>'+top.map(x=>`<th title="${x.label}">${x.label.slice(0,6)}</th>`).join('')+'</tr></thead><tbody>'+top.map(a=>`<tr><th>${a.label.slice(0,10)}</th>${top.map(b=>`<td>${assumedCorrelation(a.id,b.id).toFixed(2)}</td>`).join('')}</tr>`).join('')+'</tbody></table>'}
function renderExpectations(){const el=$('#expectationGrid');if(!el)return;const cards=[['PMI-consensus','consensusPmi','punt'],['Kerninflatie-consensus','consensusCoreCpi','%'],['ECB-consensus','consensusEcbBp',' bp'],['5Y5Y-inflatieswap','marketInflation5y5y','%']];el.innerHTML=cards.map(([label,key,unit])=>{const s=DATA.series[key],v=latest(s);return`<div><span>${label}</span><strong>${formatValue(v?.value,unit)}</strong><small>${v?fmtDate(v.date):'niet ingevuld'}</small></div>`}).join('')}
function renderDataAudit(){const el=$('#dataAuditTable');if(!el)return;el.innerHTML=Object.values(DATA.series).sort((a,b)=>(a.label||'').localeCompare(b.label||'')).map(s=>{const l=latest(s),stale=s.freshness==='verouderd'||!l;return`<tr><td>${s.label||'Onbekend'}</td><td>${fmtDate(l?.date)}</td><td>${s.source_name||s.source||'—'}</td><td><span class="source-tag ${stale?'stale':sourceClass(s.source)}">${stale?'controleer':'actueel'}</span></td></tr>`}).join('')}
function initManualForm(){const form=$('#manualForm');if(!form)return;$('#manualDate').value=new Date().toISOString().slice(0,7);form.addEventListener('submit',e=>{e.preventDefault();const val=id=>$('#'+id).value.trim().replace(',','.');const row=[val('manualDate')+'-01',val('manualPmiM'),val('manualPmiS'),val('manualPmiC'),val('manualOis3m'),val('manualOis6m'),val('manualOis12m'),val('manualSpread'),val('manual5y5y'),val('manualConsensusPmi'),val('manualConsensusCore'),val('manualConsensusEcb')].join(',');$('#manualCsvOutput').textContent=row});$('#copyManualCsv').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#manualCsvOutput').textContent);toast('CSV-regel gekopieerd')})}

const SIM_ASSETS=[
 {id:'bonds',label:'Langlopende staatsobligaties',symbol:'⌁'},
 {id:'stocks',label:'Aandelen',symbol:'↗'},
 {id:'euro',label:'Euro',symbol:'€'},
 {id:'gold',label:'Goud',symbol:'◈'},
 {id:'ig',label:'Investment Grade',symbol:'IG'},
 {id:'hy',label:'High Yield',symbol:'HY'}
];
const SIM_WEIGHTS={
 bonds:{growth:-.55,inflation:-1.05,ecb:-1.25,liquidity:.28,spread:.35},
 stocks:{growth:1.0,inflation:-.42,ecb:-.72,liquidity:.95,spread:-.72},
 euro:{growth:.30,inflation:.30,ecb:1.05,liquidity:-.30,spread:-.18},
 gold:{growth:-.18,inflation:.28,ecb:-.82,liquidity:.72,spread:.38},
 ig:{growth:.42,inflation:-.30,ecb:-.55,liquidity:.62,spread:-1.05},
 hy:{growth:.92,inflation:-.25,ecb:-.52,liquidity:.75,spread:-1.35}
};
const SIM_PRESETS={
 soft:{growth:2,inflation:-.3,ecb:-10,liquidity:.25,spread:-15},
 inflation:{growth:1,inflation:1,ecb:30,liquidity:-.5,spread:20},
 recession:{growth:-4,inflation:-.8,ecb:-40,liquidity:1.5,spread:45},
 stress:{growth:-2,inflation:0,ecb:-15,liquidity:.5,spread:150}
};
function simValues(){return{growth:+$('#simGrowth').value,inflation:+$('#simInflation').value,ecb:+$('#simEcb').value,liquidity:+$('#simLiquidity').value,spread:+$('#simSpread').value}}
function normalizeSim(v){return{growth:v.growth/3,inflation:v.inflation/.6,ecb:v.ecb/25,liquidity:v.liquidity,spread:v.spread/75}}
function signed(v,d=1,suffix=''){const sign=v>0?'+':'';return`${sign}${v.toLocaleString('nl-NL',{minimumFractionDigits:d,maximumFractionDigits:d})}${suffix}`}
function direction(score){if(score>1.35)return{arrow:'↑↑',label:'sterk positief',cls:'strong-up'};if(score>.35)return{arrow:'↑',label:'positief',cls:'up'};if(score< -1.35)return{arrow:'↓↓',label:'sterk negatief',cls:'strong-down'};if(score<-.35)return{arrow:'↓',label:'negatief',cls:'down'};return{arrow:'→',label:'gemengd / neutraal',cls:'flat'}}
function renderSimulation(){if(!$('#simGrowth'))return;const v=simValues(),n=normalizeSim(v);$('#simGrowthOutput').textContent=signed(v.growth,1,' punt');$('#simInflationOutput').textContent=signed(v.inflation,1,' pp');$('#simEcbOutput').textContent=signed(v.ecb,0,' bp');$('#simSpreadOutput').textContent=signed(v.spread,0,' bp');$('#simLiquidityOutput').textContent=v.liquidity>.35?'ruimer':v.liquidity<-.35?'krapper':'neutraal';
 const scores={};SIM_ASSETS.forEach(a=>{const w=SIM_WEIGHTS[a.id];scores[a.id]=Object.keys(n).reduce((sum,k)=>sum+n[k]*w[k],0)});
 $('#assetImpactGrid').innerHTML=SIM_ASSETS.map(a=>{const d=direction(scores[a.id]),confidence=Math.min(3,Math.max(1,Math.round(Math.abs(scores[a.id]))));return`<article class="card asset-impact ${d.cls}"><span class="asset-symbol">${a.symbol}</span><div><small>${a.label}</small><strong>${d.arrow} ${d.label}</strong><span>Modelsterkte ${'●'.repeat(confidence)}${'○'.repeat(3-confidence)}</span></div></article>`}).join('');
 const abs=Math.min(100,Math.round((Math.abs(n.growth)+Math.abs(n.inflation)+Math.abs(n.ecb)+Math.abs(n.liquidity)+Math.abs(n.spread))/8*100));$('#scenarioIntensity').textContent=`${abs}%`;$('#scenarioIntensityBar').style.width=`${abs}%`;
 const drivers=[['groei',n.growth],['inflatie',n.inflation],['ECB',n.ecb],['liquiditeit',n.liquidity],['stress',n.spread]].sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));const main=drivers[0];let title='Neutraal scenario';if(Math.abs(main[1])>.15){const words={groei:main[1]>0?'Groeiversnelling':'Groeivertraging',inflatie:main[1]>0?'Inflatieschok':'Inflatieverlichting',ECB:main[1]>0?'Hawkish ECB-verrassing':'Dovish ECB-verrassing',liquiditeit:main[1]>0?'Liquiditeitsverruiming':'Liquiditeitsverkrapping',stress:main[1]>0?'Financiële stress':'Dalende risicopremie'};title=words[main[0]]}$('#scenarioTitle').textContent=title;
 const active=drivers.filter(x=>Math.abs(x[1])>.15);$('#scenarioSummary').textContent=active.length?`${active.length} macrofactor${active.length===1?'':'en'} wijken betekenisvol af van neutraal. De pijlen tonen de gecombineerde, mechanische richting.`:'Er is nog geen betekenisvolle macroverrassing ingesteld.';
 const chain=[];if(v.growth>.5)chain.push(['Groei sterker dan verwacht','Minder noodzaak voor snelle renteverlagingen; winstvooruitzichten verbeteren.']);if(v.growth<-.5)chain.push(['Groei zwakker dan verwacht','Meer kans op renteverlagingen, maar ook druk op bedrijfswinsten en krediet.']);if(v.inflation>.15)chain.push(['Kerninflatie hoger dan verwacht','Markt prijst een langer restrictieve ECB en hogere reële rente in.']);if(v.inflation<-.15)chain.push(['Kerninflatie lager dan verwacht','Ruimte voor een dovish rentepad neemt toe.']);if(v.ecb>5)chain.push(['ECB hawkisher dan ingeprijsd','Obligatierentes en euro krijgen opwaartse druk; duration en goud tegenwind.']);if(v.ecb<-5)chain.push(['ECB dovisher dan ingeprijsd','Renteverwachtingen dalen; obligaties en liquiditeitsgevoelige activa krijgen steun.']);if(v.liquidity>.2)chain.push(['Liquiditeit neemt toe','Lagere financieringsdruk ondersteunt risicoactiva en goud.']);if(v.liquidity<-.2)chain.push(['Liquiditeit neemt af','Financiële condities verkrappen en waarderingen krijgen minder steun.']);if(v.spread>10)chain.push(['Credit spreads lopen uit','Stress stijgt; vooral High Yield en Investment Grade komen onder druk.']);if(v.spread<-10)chain.push(['Credit spreads dalen','Risicobereidheid en kredietcondities verbeteren.']);
 $('#scenarioChain').innerHTML=chain.length?chain.map((c,i)=>`<div class="chain-step"><span>${i+1}</span><div><strong>${c[0]}</strong><p>${c[1]}</p></div></div>`).join(''):'<div class="chain-empty">Beweeg een schuifregelaar of kies een voorbeeldscenario om de redeneerketen te zien.</div>';
}
function setSimulation(values){Object.entries(values).forEach(([k,v])=>{const map={growth:'simGrowth',inflation:'simInflation',ecb:'simEcb',liquidity:'simLiquidity',spread:'simSpread'};$('#'+map[k]).value=v});renderSimulation()}
function initSimulation(){if(!$('#simGrowth'))return;['simGrowth','simInflation','simEcb','simLiquidity','simSpread'].forEach(id=>$('#'+id).addEventListener('input',renderSimulation));$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>setSimulation(SIM_PRESETS[b.dataset.preset])));$('#simulationReset').addEventListener('click',()=>setSimulation({growth:0,inflation:0,ecb:0,liquidity:0,spread:0}));renderSimulation()}


function confidenceFor(s){if(!seriesValid(s))return['Geen','confidence-none'];const src=(s.source_name||s.source||'').toLowerCase();if(src.includes('eurostat')||src.includes('ecb')||src.includes('bundesbank'))return['Hoog','confidence-high'];if(src.includes('fred')||src.includes('ice')||src.includes('s&p'))return['Redelijk','confidence-medium'];if(src.includes('hand'))return['Laag','confidence-low'];return['Redelijk','confidence-medium']}
function renderRecession(){if(!$('#recessionProbability'))return;const get=k=>latest(DATA.series[k])?.value, clamp=x=>Math.max(0,Math.min(1,x)), parts=[];const add=(label,value,score,rule)=>{if(value!=null&&Number.isFinite(score))parts.push({label,value,score:clamp(score),rule})};const pmi=get('pmiComposite');add('PMI composite',pmi,(51-pmi)/4,'51 of hoger = weinig stress; 47 of lager = maximale stress');const curve=get('yieldCurve');add('Rentecurve 10Y–2Y',curve,(.5-curve)/1.5,'+0,5 pp = weinig stress; −1,0 pp = maximale stress');const und=deltaAt(DATA.series.unemployment,6);add('Werkloosheid, 6m verandering',und,(und+.1)/.8,'−0,1 pp = weinig stress; +0,7 pp = maximale stress');const spread=get('creditSpread');add('Euro HY OAS',spread,(spread-2)/4,'2% = weinig stress; 6% = maximale stress');const m3=get('m3');add('M3-groei',m3,(2-m3)/5,'2% of hoger = weinig stress; −3% = maximale stress');const gdp=get('gdp');add('BBP q-o-q',gdp,(.4-gdp)/1,'+0,4% = weinig stress; −0,6% = maximale stress');const prob=parts.length?Math.round((parts.reduce((a,b)=>a+b.score,0)/parts.length)*70+5):null;$('#recessionProbability').textContent=prob==null?'—':`${prob}%`;$('#recessionLabel').textContent=prob==null?'onvoldoende data':prob<20?'laag':prob<40?'gematigd':prob<60?'verhoogd':'hoog';$('#recessionConfidence').textContent=parts.length>=5?'redelijk':parts.length>=3?'beperkt':'laag';const breakdown=$('#recessionBreakdown');if(breakdown)breakdown.innerHTML=parts.map(x=>`<div><span><strong>${x.label}</strong><small>${x.rule}</small></span><b>${Number(x.value).toLocaleString('nl-NL',{maximumFractionDigits:2})}</b><em>${Math.round(x.score*100)}/100 stress</em><i style="width:${x.score*100}%"></i></div>`).join('')||'<p>Onvoldoende geldige data.</p>'} 
function setupRecessionExplanation(){const b=$('#recessionExplainBtn'),panel=$('#recessionExplanation');if(!b||!panel)return;b.addEventListener('click',()=>{panel.hidden=!panel.hidden;b.textContent=panel.hidden?'Bekijk volledige berekening':'Verberg berekening'})}
function renderMarketComparison(){const root=$('#marketComparison');if(!root)return;const v=id=>Number($('#'+id)?.value)||0;const rows=[['Groei (PMI)',v('euPmi'),v('usPmi'),false],['Kerninflatie',v('euCore'),v('usCore'),true],['Beleidsrente',v('euPolicy'),v('usPolicy'),true],['10-jaarsrente',v('euYield'),v('usYield'),true],['Earnings yield',100/Math.max(v('euPe'),.1),100/Math.max(v('usPe'),.1),true],['HY OAS',v('euHy'),v('usHy'),true]];root.innerHTML=rows.map(([n,eu,us,pct])=>{const diff=eu-us;return`<div><strong>${n}</strong><span>Eurozone <b>${eu.toLocaleString('nl-NL',{maximumFractionDigits:2})}${pct?'%':''}</b></span><span>VS <b>${us.toLocaleString('nl-NL',{maximumFractionDigits:2})}${pct?'%':''}</b></span><em>${diff>0?'+':''}${diff.toLocaleString('nl-NL',{maximumFractionDigits:2})}${pct?' pp':''}</em></div>`}).join('')}
function setupMarketComparison(){$$('.market-inputs input').forEach(i=>i.addEventListener('input',renderMarketComparison));renderMarketComparison()}
const VALUATION_DATA=[
 {name:'Eurozone breed',index:'MSCI EMU',trailing:18.84,forward:15.32,dividend:2.70,source:'MSCI EMU'},
 {name:'Groei-aandelen',index:'MSCI Europe Growth',trailing:24.19,forward:20.37,dividend:1.69,source:'MSCI Europe Growth'},
 {name:'Value-aandelen',index:'MSCI Europe Value',trailing:14.33,forward:11.82,dividend:3.94,source:'MSCI Europe Value'},
 {name:'Prijszettingsmacht-proxy',index:'MSCI EMU Universal',trailing:17.82,forward:14.65,dividend:2.87,source:'MSCI EMU Universal',proxy:true}
];
function renderValuation(){
 if(!$('#valuationResults'))return;
 const bund=latest(DATA?.series?.bund10y)?.value;
 const euro10=latest(DATA?.series?.yield10y)?.value;
 const bond=Number.isFinite(bund)?bund:Number.isFinite(euro10)?euro10:1.96;
 const bondLabel=Number.isFinite(bund)?'Duitse Bund 10Y':Number.isFinite(euro10)?'ECB eurozone-benchmark 10Y':'Vaste fallback';
 const rows=VALUATION_DATA.map(x=>({...x,earnings:100/x.forward,premium:100/x.forward-bond}));
 $('#valuationTableBody').innerHTML=rows.map(x=>`<tr><td><strong>${x.name}</strong><small>${x.index}${x.proxy?' · proxy':''}</small></td><td>${x.trailing.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}x</td><td>${x.forward.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}x</td><td><strong>${x.earnings.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}%</strong></td><td>${x.dividend.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}%</td><td>${x.premium>=0?'+':''}${x.premium.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})} pp</td></tr>`).join('');
 const cheapest=[...rows].sort((a,b)=>a.forward-b.forward)[0],priciest=[...rows].sort((a,b)=>b.forward-a.forward)[0];
 $('#valuationSummary').innerHTML=`<article class="card valuation-hero"><span class="eyebrow">LAAGSTE FORWARD K/W</span><strong>${cheapest.name}</strong><b>${cheapest.forward.toLocaleString('nl-NL',{minimumFractionDigits:2})}x</b><small>Earnings yield ${cheapest.earnings.toLocaleString('nl-NL',{maximumFractionDigits:2})}%</small></article><article class="card valuation-hero"><span class="eyebrow">HOOGSTE FORWARD K/W</span><strong>${priciest.name}</strong><b>${priciest.forward.toLocaleString('nl-NL',{minimumFractionDigits:2})}x</b><small>Earnings yield ${priciest.earnings.toLocaleString('nl-NL',{maximumFractionDigits:2})}%</small></article><article class="card valuation-hero"><span class="eyebrow">RENTEVERGELIJKING</span><strong>${bondLabel}</strong><b>${bond.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}%</b><small>Gebruikt voor de eenvoudige winstpremie</small></article>`;
 $('#valuationResults').innerHTML=`<div><span>Value versus groei</span><strong>Value noteert ${(priciest.forward/cheapest.forward-1)*100>=0?((priciest.forward/cheapest.forward-1)*100).toLocaleString('nl-NL',{maximumFractionDigits:0}):'—'}% lager op forward K/W</strong><small>Dit kan een waarderingskans zijn, maar weerspiegelt ook andere sectoren en groeiverwachtingen.</small></div><div><span>Breed eurozone</span><strong>Earnings yield ${rows[0].earnings.toLocaleString('nl-NL',{maximumFractionDigits:2})}%</strong><small>Eenvoudige premie boven ${bondLabel}: ${rows[0].premium.toLocaleString('nl-NL',{maximumFractionDigits:2})} pp.</small></div><div><span>Prijszettingsmacht</span><strong>Proxy, geen zuivere index</strong><small>MSCI EMU Universal benadert robuustheid en kwaliteit, maar meet prijszettingsmacht niet rechtstreeks.</small></div>`;
 $('#valuationBondSource').textContent=`${bondLabel} · ${latest(DATA?.series?.bund10y)?.date?fmtDate(latest(DATA.series.bund10y).date):latest(DATA?.series?.yield10y)?.date?fmtDate(latest(DATA.series.yield10y).date):'fallback'}`;
}
const REGIMES=[
['1929–1933','Grote Depressie','instorting','deflatie','bankencrisis en beleidsfouten','Cash en hoogwaardige staatsobligaties hielden relatief beter stand.'],['1933–1939','Herstel en New Deal','herstel','lage inflatie','reflatie en overheidsingrijpen','Aandelen herstelden sterk maar met grote volatiliteit.'],['1939–1945','Oorlogseconomie','zeer sterk','rantsoenering/inflatie','financiële repressie','Nominale rendementen werden gestuurd; reële koopkracht stond onder druk.'],['1946–1951','Naoorlogse inflatie','sterk','hoog','schaarste en wederopbouw','Reële activa en prijszettingsmacht waren belangrijk.'],['1952–1965','Gouden groeijaren','sterk','gematigd','productiviteit en wederopbouw','Aandelen en krediet profiteerden.'],['1966–1982','Stagflatie','zwak/volatiel','hoog','olie, lonen en monetair beleid','Grondstoffen, goud en inflatiebescherming hielpen; duration leed.'],['1982–1990','Desinflatie en expansie','sterk','dalend','Volcker-effect en liberalisering','Lange obligaties en aandelen profiteerden.'],['1990–2000','Globalisering en technologie','groei','laag','globalisering en productiviteit','Groei-aandelen domineerden richting de dotcombubbel.'],['2000–2003','Dotcom-bust','recessie','laag','waarderingscorrectie','Value en hoogwaardige obligaties hielden beter stand.'],['2003–2007','Kredietexpansie','sterk','gematigd','hefboom en huizenmarkt','Risicoactiva stegen; kwetsbaarheid bouwde op.'],['2008–2009','Grote Financiële Crisis','instorting','desinflatie','banken- en kredietcrisis','Staatsobligaties en cash diversifieerden; HY en aandelen kelderden.'],['2010–2012','Eurocrisis','zwak','laag','soevereine spreads en bezuiniging','Duitse Bunds fungeerden als veilige haven.'],['2013–2019','Lage inflatie en QE','gematigd','te laag','QE en negatieve rente','Duration, groei en vastgoed profiteerden.'],['2020','Pandemische recessie','instorting/herstel','laag','lockdowns en uitzonderlijke stimulans','Eerst cash/duration, daarna brede risicoactiva.'],['2021','Heropening','sterk','oplopend','vraagherstel en aanbodknelpunten','Cyclisch, value en grondstoffen profiteerden.'],['2022–2023','Inflatieschok en verkrapping','zwakker','hoog','energie en snelle renteverhogingen','Cash, value en grondstoffen beter; lange duration zwak.'],['2024–2025','Desinflatie en normalisatie','gematigd','dalend','inflatie daalt, rente blijft restrictief','Selectieve groei en krediet met aandacht voor waardering.'],['2026','Huidig overgangsregime','positief maar kwetsbaar','rond/boven doel','energie, geopolitiek en rentepad','Scenario-afhankelijk; diversificatie belangrijk.']];
function renderRegimes(){const root=$('#regimeTimeline');if(!root)return;root.innerHTML=REGIMES.map((r,i)=>`<button data-regime="${i}"><span>${r[0]}</span><strong>${r[1]}</strong></button>`).join('');root.onclick=e=>{const b=e.target.closest('[data-regime]');if(!b)return;const r=REGIMES[+b.dataset.regime];$$('[data-regime]',root).forEach(x=>x.classList.toggle('active',x===b));$('#regimeDetail').innerHTML=`<span class="eyebrow">${r[0]}</span><h3>${r[1]}</h3><div class="regime-facts"><div><small>Groei</small><strong>${r[2]}</strong></div><div><small>Inflatie</small><strong>${r[3]}</strong></div><div><small>Drijver</small><strong>${r[4]}</strong></div></div><p>${r[5]}</p>`};root.querySelector('button:last-child')?.click()}

function initRangePickers(){$$('[data-range-picker]').forEach(el=>{el.innerHTML=Object.keys(RANGE_MONTHS).map(r=>`<button class="${r===currentRange?'active':''}" data-range="${r}">${r}</button>`).join('');el.addEventListener('click',e=>{const b=e.target.closest('button[data-range]');if(!b)return;currentRange=b.dataset.range;localStorage.setItem('macrovisie-range',currentRange);$$('[data-range-picker] button').forEach(x=>x.classList.toggle('active',x.dataset.range===currentRange));renderAll()})})}
function showTooltip(e,html){tooltip=$('#tooltip');tooltip.innerHTML=html;tooltip.hidden=false;moveTooltip(e)}function moveTooltip(e){if(!tooltip)return;tooltip.style.left=`${Math.min(e.clientX+14,window.innerWidth-190)}px`;tooltip.style.top=`${Math.min(e.clientY+14,window.innerHeight-100)}px`}function hideTooltip(){if(tooltip)tooltip.hidden=true}
function navigate(page){currentPage=PAGE_META[page]?page:'dashboard';$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.pagePanel===currentPage));$$('#nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===currentPage));$('#eyebrow').textContent=PAGE_META[currentPage][0];$('#pageTitle').textContent=PAGE_META[currentPage][1];closeSidebar();window.scrollTo({top:0,behavior:'instant'})}
function openSidebar(){$('#sidebar').classList.add('open');$('#scrim').hidden=false}function closeSidebar(){$('#sidebar').classList.remove('open');$('#scrim').hidden=true}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('macrovisie-theme',theme);document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#07111f':'#eef3f8'}
function commandItems(){const pages=Object.entries(PAGE_META).map(([id,m])=>({label:m[1],meta:'Pagina',target:id}));const indicators=Object.entries(DATA.series).map(([id,s])=>({label:s.label,meta:s.category||'Indicator',target:TARGET_PAGE[id]||'dashboard'}));return[...pages,...indicators]}
function renderCommands(query=''){const q=query.trim().toLowerCase(),items=commandItems().filter(i=>!q||`${i.label} ${i.meta}`.toLowerCase().includes(q)).slice(0,18);commandIndex=Math.min(commandIndex,Math.max(0,items.length-1));$('#commandResults').innerHTML=items.map((i,n)=>`<button class="command-item ${n===commandIndex?'active':''}" data-target="${i.target}"><span>${i.label}</span><small>${i.meta}</small></button>`).join('')||'<div class="chart-empty">Geen resultaten</div>';$$('.command-item').forEach(b=>b.addEventListener('click',()=>{location.hash=b.dataset.target;$('#commandDialog').close()}))}
function openCommand(){commandIndex=0;renderCommands();$('#commandDialog').showModal();setTimeout(()=>$('#commandInput').focus(),20)}
function setupEvents(){window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));$('#menuBtn').addEventListener('click',openSidebar);$('#sidebarClose').addEventListener('click',closeSidebar);$('#scrim').addEventListener('click',closeSidebar);$$('.info-button').forEach(b=>b.addEventListener('click',()=>{const[t,d]=DEFINITIONS[b.dataset.info]||['Begrip','Geen uitleg beschikbaar.'];$('#dialogTitle').textContent=t;$('#dialogBody').innerHTML=`<p>${d}</p>`;$('#infoDialog').showModal()}));$('#dialogClose').addEventListener('click',()=>$('#infoDialog').close());$('#downloadBtn').addEventListener('click',downloadCsv);$('#themeBtn').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));$('#searchLaunch').addEventListener('click',openCommand);$('#commandInput').addEventListener('input',e=>{commandIndex=0;renderCommands(e.target.value)});$('#commandInput').addEventListener('keydown',e=>{const items=$$('.command-item');if(e.key==='ArrowDown'){e.preventDefault();commandIndex=Math.min(commandIndex+1,items.length-1);renderCommands(e.currentTarget.value)}if(e.key==='ArrowUp'){e.preventDefault();commandIndex=Math.max(commandIndex-1,0);renderCommands(e.currentTarget.value)}if(e.key==='Enter'&&items[commandIndex])items[commandIndex].click()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();openCommand()}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true})}
function downloadCsv(){const keys=currentPage==='dashboard'?Object.keys(DATA.series):(PAGE_KEYS[currentPage]||Object.keys(DATA.series)),rows=['indicator,date,value,unit,source'];keys.forEach(k=>DATA.series[k]?.values?.forEach(v=>rows.push([k,v.date,v.value,DATA.series[k].unit,DATA.series[k].source].map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(','))));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download=`macrovisie-${currentPage}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSV is gedownload')}
async function load(){applyTheme(localStorage.getItem('macrovisie-theme')||'dark');try{const r=await fetch(`data/dashboard.json?ts=${Date.now()}`);if(!r.ok)throw Error();DATA=await r.json();$('#globalSource').textContent='Data beschikbaar';$('#stateDot').classList.add('good')}catch(e){const r=await fetch('data/sample.json');DATA=await r.json();$('#globalSource').textContent='Voorbeelddata';$('#sourceNote').textContent='Live bestand niet gevonden';$('#stateDot').classList.add('bad')}$('#lastUpdated').textContent=DATA.meta?.updated_at?fmtDate(DATA.meta.updated_at):'—';initRangePickers();renderDefinitions();renderAll();renderRecession();initSimulation();initManualForm();renderPortfolio();renderValuation();renderRegimes();renderMarketComparison();setupRecessionExplanation();setupMarketComparison();setupEvents();navigate(location.hash.slice(1)||'dashboard');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
load();
